-- Generado por Oracle SQL Developer Data Modeler 4.2.0.921
--   en:        2018-09-12 20:33:22 COT
--   sitio:      Oracle Database 11g
--   tipo:      Oracle Database 11g



CREATE TABLE ACCESOS
  (
    id     INTEGER NOT NULL,
    nombre VARCHAR (60) NOT NULL ,
    url    VARCHAR (200) NOT NULL
  ) ;
ALTER TABLE ACCESOS ADD CONSTRAINT ACCESOS_PK PRIMARY KEY ( id ) ;
ALTER TABLE `ACCESOS` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

CREATE TABLE ARCHIVO_INMUEBLE
  (
    id       INTEGER NOT NULL ,
    tipo     INTEGER NOT NULL ,
    nombre   VARCHAR (300) NOT NULL ,
    Inmueble INTEGER NOT NULL
  ) ;
ALTER TABLE ARCHIVO_INMUEBLE ADD CONSTRAINT FOTOS_INMUEBLE_PK PRIMARY KEY ( id ) ;
ALTER TABLE `ARCHIVO_INMUEBLE` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

CREATE TABLE ARRIENDO
  (
    id       INTEGER NOT NULL ,
    Contrato INTEGER NOT NULL ,
    Empleado INTEGER NOT NULL
  ) ;
ALTER TABLE ARRIENDO ADD CONSTRAINT ARRIENDO_PK PRIMARY KEY ( id ) ;
ALTER TABLE `ARRIENDO` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

CREATE TABLE CARGOS
  (
    id          INTEGER NOT NULL ,
    nombre      VARCHAR (100) NOT NULL ,
    descripcion VARCHAR (300) NOT NULL
  ) ;
ALTER TABLE CARGOS ADD CONSTRAINT CARGOS_PK PRIMARY KEY ( id ) ;
ALTER TABLE `CARGOS` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

CREATE TABLE CAUCION
  (
    id          INTEGER NOT NULL ,
    descripcion VARCHAR (1000) NOT NULL ,
    Arriendo    INTEGER NOT NULL
  ) ;
ALTER TABLE CAUCION ADD CONSTRAINT CAUCION_PK PRIMARY KEY ( id ) ;
ALTER TABLE `CAUCION` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

CREATE TABLE CITA_DESALOJO
  (
    id       INTEGER NOT NULL,
    fecha    DATE NOT NULL ,
    Arriendo INTEGER NOT NULL ,
    Empleado INTEGER NOT NULL
  ) ;
ALTER TABLE CITA_DESALOJO ADD CONSTRAINT CITA_DESALOJO_PK PRIMARY KEY ( id ) ;
ALTER TABLE `CITA_DESALOJO` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

CREATE TABLE CIUDADES
  (
    id           INTEGER NOT NULL,
    nombre       VARCHAR (100) NOT NULL ,
    departamento INTEGER NOT NULL
  ) ;
ALTER TABLE CIUDADES ADD CONSTRAINT CIUDADES_PK PRIMARY KEY ( id ) ;
ALTER TABLE `CIUDADES` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

CREATE TABLE CONTRATO
  (
    id          INTEGER NOT NULL,
    descripcion VARCHAR (1000) ,
    Empleado    INTEGER NOT NULL ,
    Cliente     INTEGER NOT NULL ,
    Visita      INTEGER NOT NULL
  ) ;
ALTER TABLE CONTRATO ADD CONSTRAINT CONTRATO_PK PRIMARY KEY ( id ) ;
ALTER TABLE `CONTRATO` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

CREATE TABLE DEPARTAMENTOS
  (
    id     INTEGER NOT NULL,
    nombre VARCHAR (100) NOT NULL
  ) ;
ALTER TABLE DEPARTAMENTOS ADD CONSTRAINT DEPARTAMENTOS_PK PRIMARY KEY ( id ) ;
ALTER TABLE `DEPARTAMENTOS` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

CREATE TABLE EMPLEADOS
  (
    persona     INTEGER NOT NULL,
    profesion   VARCHAR (200) ,
    experiencia VARCHAR (200) ,
    Cargo       INTEGER NOT NULL
  ) ;
ALTER TABLE EMPLEADOS ADD CONSTRAINT EMPLEADOS_PK PRIMARY KEY ( persona ) ;

CREATE TABLE EXPERIENCIAS
  (
    id                 INTEGER NOT NULL,
    empresa            VARCHAR (200) NOT NULL ,
    empresa_direccion  VARCHAR (100) NOT NULL ,
    empresa_telefono   VARCHAR (100) NOT NULL ,
    cargo              VARCHAR (100) NOT NULL ,
    fecha_inicio       DATE NOT NULL ,
    fecha_fin          DATE NOT NULL ,
    file_certificacion VARCHAR (200) NOT NULL ,
    Empleado           INTEGER NOT NULL
  ) ;
ALTER TABLE EXPERIENCIAS ADD CONSTRAINT EXPERIENCIAS_PK PRIMARY KEY ( id ) ;
ALTER TABLE `EXPERIENCIAS` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

CREATE TABLE FORMACIONES
  (
    id                 INTEGER NOT NULL,
    institucion        VARCHAR (100) NOT NULL ,
    titulo             VARCHAR (100) NOT NULL ,
    file_certificacion VARCHAR (300) NOT NULL ,
    Empleado           INTEGER NOT NULL
  ) ;
ALTER TABLE FORMACIONES ADD CONSTRAINT FORMACIONES_PK PRIMARY KEY ( id ) ;
ALTER TABLE `FORMACIONES` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

CREATE TABLE FORMATO_VENTAS
  (
    id       INTEGER NOT NULL,
    fecha    DATE NOT NULL ,
    Inmueble INTEGER NOT NULL ,
    Empleado INTEGER NOT NULL
  ) ;
ALTER TABLE FORMATO_VENTAS ADD CONSTRAINT FORMATO_VENTAS_PK PRIMARY KEY ( id ) ;
ALTER TABLE `FORMATO_VENTAS` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

CREATE TABLE INFORME
  (
    id          INTEGER NOT NULL ,
    fecha       DATE NOT NULL ,
    descripcion VARCHAR (1000) NOT NULL ,
    ARRIENDO_id INTEGER NOT NULL
  ) ;
ALTER TABLE INFORME ADD CONSTRAINT INFORME_PK PRIMARY KEY ( id ) ;
ALTER TABLE `INFORME` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

CREATE TABLE INMUEBLE
  (
    id                         INTEGER NOT NULL,
    numero_matricula           VARCHAR (100) NOT NULL ,
    direccion                  VARCHAR (100) NOT NULL ,
    area                       INTEGER NOT NULL ,
    valor                      INTEGER NOT NULL ,
    banios                     INTEGER NOT NULL ,
    estado                     INTEGER NOT NULL ,
    tipoVentaArrendo           INTEGER NOT NULL ,
    garajes                    INTEGER NOT NULL ,
    antiguedad                 INTEGER NOT NULL ,
    detalles                   VARCHAR (400) NOT NULL ,
    añoConstruccion            VARCHAR (20) NOT NULL ,
    ascensor                   CHAR (1) NOT NULL ,
    canchas_deportivas         CHAR (1) NOT NULL ,
    zonas_humedas              CHAR (1) NOT NULL ,
    zona_infantil              CHAR (1) NOT NULL ,
    Jardines                   CHAR (1) NOT NULL ,
    transporte_publico_cercano CHAR (1) NOT NULL ,
    precio_negociable          CHAR (1) NOT NULL ,
    zona_ropas                 CHAR (1) NOT NULL ,
    parqueadero                CHAR (1) NOT NULL ,
    deposito                   CHAR (1) NOT NULL ,
    estudio                    CHAR (1) ,
    tipo_cortinas              VARCHAR (100) NOT NULL ,
    cuarto_servicio            CHAR (1) NOT NULL ,
    chimenea                   CHAR (1) NOT NULL ,
    cocinaAbiertaCerrada       CHAR (1) NOT NULL ,
    comedorIndependiente       CHAR (1) NOT NULL ,
    vista_exterior_interior    CHAR (1) NOT NULL ,
    zona                       INTEGER NOT NULL ,
    aprobacion_fecha           DATE ,
    Tipo                       INTEGER NOT NULL ,
    Ciudad                     INTEGER NOT NULL ,
    Usuario                    INTEGER NOT NULL ,
    Administrador              INTEGER ,
    Promocion                  INTEGER
  ) ;
ALTER TABLE INMUEBLE ADD CONSTRAINT INMUEBLE_PK PRIMARY KEY ( id ) ;
ALTER TABLE `INMUEBLE` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;
ALTER TABLE INMUEBLE ADD UNIQUE (numero_matricula);

CREATE TABLE PERSONAS
  (
    id               INTEGER NOT NULL,
    cedula           VARCHAR (20) NOT NULL ,
    nombre           VARCHAR (40) NOT NULL ,
    apellido         VARCHAR (40) NOT NULL ,
    fecha_nacimiento DATE NOT NULL ,
    telefono         VARCHAR (10) NOT NULL ,
    direccion        VARCHAR (50) NOT NULL ,
    rol              INTEGER NOT NULL
  ) ;
ALTER TABLE PERSONAS ADD CONSTRAINT PERSONAS_PK PRIMARY KEY ( id ) ;
ALTER TABLE PERSONAS ADD CONSTRAINT PERSONAS__UN UNIQUE ( cedula ) ;
ALTER TABLE `PERSONAS` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

CREATE TABLE PROMOCION
  (
    id          INTEGER NOT NULL,
    descripcion VARCHAR (100) NOT NULL ,
    porcentaje  INTEGER NOT NULL ,
    fecha       DATE NOT NULL
  ) ;
ALTER TABLE PROMOCION ADD CONSTRAINT PROMOCION_PK PRIMARY KEY ( id ) ;
ALTER TABLE `PROMOCION` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

CREATE TABLE REPORTES_VISITAS
  (
    id       INTEGER NOT NULL,
    fecha    DATE NOT NULL ,
    Inmueble INTEGER NOT NULL ,
    Usuario  INTEGER NOT NULL
  ) ;
ALTER TABLE REPORTES_VISITAS ADD CONSTRAINT REPORTES_VISITAS_PK PRIMARY KEY ( id ) ;
ALTER TABLE `REPORTES_VISITAS` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

CREATE TABLE RESERVAR_VISITA
  (
    id       INTEGER NOT NULL,
    mensaje  VARCHAR (600) NOT NULL ,
    fecha    DATE ,
    estado   INTEGER NOT NULL ,
    Inmueble INTEGER NOT NULL ,
    Cliente  INTEGER NOT NULL ,
    Empleado INTEGER NOT NULL
  ) ;
ALTER TABLE RESERVAR_VISITA ADD CONSTRAINT RESERVAR_VISITA_PK PRIMARY KEY ( id ) ;
ALTER TABLE `RESERVAR_VISITA` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

CREATE TABLE REUNION
  (
    id          INTEGER NOT NULL ,
    fecha       DATE NOT NULL ,
    descripcion VARCHAR (1000) NOT NULL ,
    Persona     INTEGER NOT NULL
  ) ;
ALTER TABLE REUNION ADD CONSTRAINT Reunion_PK PRIMARY KEY ( id ) ;
ALTER TABLE `REUNION` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

CREATE TABLE ROLES
  (
    id          INTEGER NOT NULL,
    nombre      VARCHAR (30) NOT NULL ,
    descripcion VARCHAR (200) NOT NULL
  ) ;
ALTER TABLE ROLES ADD CONSTRAINT TIPO_PERSONAL_PK PRIMARY KEY ( id ) ;
ALTER TABLE `ROLES` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

CREATE TABLE ROL_ACCESOS
  ( Rol INTEGER NOT NULL , Acceso INTEGER NOT NULL
  ) ;
ALTER TABLE ROL_ACCESOS ADD CONSTRAINT ROL_ACCESOS_PK PRIMARY KEY ( Rol, Acceso ) ;

CREATE TABLE TIPO_INMUEBLE
  (
    id          INTEGER NOT NULL,
    nombre      VARCHAR (50) NOT NULL ,
    descripcion VARCHAR (300) NOT NULL
  ) ;
ALTER TABLE TIPO_INMUEBLE ADD CONSTRAINT TIPO_INMUEBLE_PK PRIMARY KEY ( id ) ;
ALTER TABLE `TIPO_INMUEBLE` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

CREATE TABLE USUARIOS
  (
    Persona  INTEGER NOT NULL ,
    username VARCHAR (100) NOT NULL ,
    password VARCHAR (100) NOT NULL
  ) ;
ALTER TABLE USUARIOS ADD CONSTRAINT USUARIO_PK PRIMARY KEY ( Persona ) ;
ALTER TABLE USUARIOS ADD CONSTRAINT USUARIO__UN UNIQUE ( Persona ) ;

CREATE TABLE VENTA
  (
    id       INTEGER NOT NULL ,
    Contrato INTEGER NOT NULL ,
    Empleado INTEGER NOT NULL
  ) ;
ALTER TABLE VENTA ADD CONSTRAINT VENTA_PK PRIMARY KEY ( id ) ;
ALTER TABLE `VENTA` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE ARRIENDO ADD CONSTRAINT ARRIENDO_CONTRATO_FK FOREIGN KEY ( Contrato ) REFERENCES CONTRATO ( id ) ;

ALTER TABLE ROL_ACCESOS ADD CONSTRAINT Acceso FOREIGN KEY ( Acceso ) REFERENCES ACCESOS ( id ) ;

ALTER TABLE CAUCION ADD CONSTRAINT Arriendo FOREIGN KEY ( Arriendo ) REFERENCES ARRIENDO ( id ) ;

ALTER TABLE INFORME ADD CONSTRAINT Arriendov2 FOREIGN KEY ( ARRIENDO_id ) REFERENCES ARRIENDO ( id ) ;

ALTER TABLE CITA_DESALOJO ADD CONSTRAINT CITA_DESALOJO_ARRIENDO_FK FOREIGN KEY ( Arriendo ) REFERENCES ARRIENDO ( id ) ;

ALTER TABLE CIUDADES ADD CONSTRAINT CIUDADES_DEPARTAMENTOS_FK FOREIGN KEY ( departamento ) REFERENCES DEPARTAMENTOS ( id ) ;

ALTER TABLE VENTA ADD CONSTRAINT Contraro FOREIGN KEY ( Contrato ) REFERENCES CONTRATO ( id ) ;

ALTER TABLE EMPLEADOS ADD CONSTRAINT EMPLEADOS_CARGOS_FK FOREIGN KEY ( Cargo ) REFERENCES CARGOS ( id ) ;

ALTER TABLE EMPLEADOS ADD CONSTRAINT EMPLEADOS_PERSONAS_FK FOREIGN KEY ( persona ) REFERENCES PERSONAS ( id ) ;

ALTER TABLE EXPERIENCIAS ADD CONSTRAINT EXPERIENCIAS_EMPLEADOS_FK FOREIGN KEY ( Empleado ) REFERENCES EMPLEADOS ( persona ) ;

ALTER TABLE RESERVAR_VISITA ADD CONSTRAINT Empleado FOREIGN KEY ( Empleado ) REFERENCES PERSONAS ( id ) ;

ALTER TABLE VENTA ADD CONSTRAINT Empleadov2 FOREIGN KEY ( Empleado ) REFERENCES PERSONAS ( id ) ;

ALTER TABLE ARRIENDO ADD CONSTRAINT Empleadov3 FOREIGN KEY ( Empleado ) REFERENCES PERSONAS ( id ) ;

ALTER TABLE CITA_DESALOJO ADD CONSTRAINT Empleadov5 FOREIGN KEY ( Empleado ) REFERENCES PERSONAS ( id ) ;

ALTER TABLE FORMATO_VENTAS ADD CONSTRAINT Empleadov6 FOREIGN KEY ( Empleado ) REFERENCES PERSONAS ( id ) ;

ALTER TABLE FORMACIONES ADD CONSTRAINT FORMACIONES_EMPLEADOS_FK FOREIGN KEY ( Empleado ) REFERENCES EMPLEADOS ( persona ) ;

ALTER TABLE ARCHIVO_INMUEBLE ADD CONSTRAINT FOTOS_INMUEBLE_INMUEBLE_FK FOREIGN KEY ( Inmueble ) REFERENCES INMUEBLE ( id ) ;

ALTER TABLE INMUEBLE ADD CONSTRAINT INMUEBLE_CIUDADES_FK FOREIGN KEY ( Ciudad ) REFERENCES CIUDADES ( id ) ;

ALTER TABLE INMUEBLE ADD CONSTRAINT INMUEBLE_PROMOCION_FK FOREIGN KEY ( Promocion ) REFERENCES PROMOCION ( id ) ;

ALTER TABLE INMUEBLE ADD CONSTRAINT INMUEBLE_USUARIOS_FK FOREIGN KEY ( Usuario ) REFERENCES USUARIOS ( Persona ) ;

ALTER TABLE INMUEBLE ADD CONSTRAINT INMUEBLE_USUARIOS_FKv2 FOREIGN KEY ( Administrador ) REFERENCES USUARIOS ( Persona ) ;

ALTER TABLE FORMATO_VENTAS ADD CONSTRAINT Inmueble FOREIGN KEY ( Inmueble ) REFERENCES INMUEBLE ( id ) ;

ALTER TABLE PERSONAS ADD CONSTRAINT PERSONAS_ROLES_FK FOREIGN KEY ( rol ) REFERENCES ROLES ( id ) ;

ALTER TABLE REUNION ADD CONSTRAINT Persona FOREIGN KEY ( Persona ) REFERENCES PERSONAS ( id ) ;

ALTER TABLE CONTRATO ADD CONSTRAINT Personav1 FOREIGN KEY ( Empleado ) REFERENCES PERSONAS ( id ) ;

ALTER TABLE CONTRATO ADD CONSTRAINT Personav3 FOREIGN KEY ( Cliente ) REFERENCES PERSONAS ( id ) ;

ALTER TABLE CONTRATO ADD CONSTRAINT RESERVAR_VISITA FOREIGN KEY ( Visita ) REFERENCES RESERVAR_VISITA ( id ) ;

ALTER TABLE RESERVAR_VISITA ADD CONSTRAINT RES_VISITA_INM_FK FOREIGN KEY ( Inmueble ) REFERENCES INMUEBLE ( id ) ;

ALTER TABLE ROL_ACCESOS ADD CONSTRAINT Rol FOREIGN KEY ( Rol ) REFERENCES ROLES ( id ) ;

ALTER TABLE INMUEBLE ADD CONSTRAINT TIPO_INMUEBLE_FK FOREIGN KEY ( Tipo ) REFERENCES TIPO_INMUEBLE ( id ) ;

ALTER TABLE USUARIOS ADD CONSTRAINT USUARIO_PERSONAS_FK FOREIGN KEY ( Persona ) REFERENCES PERSONAS ( id ) ;

ALTER TABLE RESERVAR_VISITA ADD CONSTRAINT VISITA_PERSONAS_FK FOREIGN KEY ( Cliente ) REFERENCES PERSONAS ( id ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            25
-- CREATE INDEX                             0
-- ALTER TABLE                             59
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0